[project]
name = "chatix-text"
version = "0.1.0"
description = "Text messages microservice for chatix project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
]
