spring:
  application:
    name: chatix-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${CX_DB_URL}
    username: ${CX_DB_USERNAME}
    password: ${CX_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  task:
    scheduling:
      pool:
        size: 5


server:
  port: 8080
